import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class NavigationService {
  navBackend: any[] = [
    {
      displayName: 'Tablero',
      iconName: ['home'],
      material: true,
      route: 'backend/dashboard',
      display: true,
    },
    {
      displayName: 'Sistema',
      iconName: ['dashboard'],
      material: true,
      children: [
        {
          displayName: 'Usuarios',
          iconName: ['perm_identity'],
          route: 'user',
          material: true,
          display: true,
        },
        {
          displayName: 'Entidades',
          iconName: ['domain'],
          material: true,
          children: [
            {
              displayName: 'Ubicación Organizacional',
              iconName: ['account_balance'],
              route: 'org-level',
              material: true,
              display: true,
            },
            {
              displayName: 'Unidad de Salud',
              iconName: ['local_hospital'],
              route: 'health-unit',
              material: true,
              display: true,
            },
            {
              displayName: 'Departamento',
              iconName: ['location_city'],
              route: 'office',
              material: true,
              display: true,
            },
            {
              displayName: 'Puesto de Trabajo',
              iconName: ['store'],
              route: 'work-station',
              material: true,
              display: true,
            },
          ],
          display: true,
        },
        {
          displayName: 'Sistema',
          iconName: ['line_style'],
          route: 'sistem',
          material: true,
          display: true,
        },
        {
          displayName: 'Seguridad',
          iconName: ['lock'],
          material: true,
          children: [
            {
              displayName: 'Roles',
              iconName: ['assignment_ind'],
              route: 'roles',
              material: true,
              display: true,
            },
            {
              displayName: 'Historial de acceso',
              iconName: ['receipt'],
              route: 'trace-access',
              material: true,
              display: true,
            },
            {
              displayName: 'Historial de acciones',
              iconName: ['list_alt'],
              route: 'trace-actions',
              material: true,
              display: true,
            },
          ],
          display: true,
        },
        {
          displayName: 'Clasificadores',
          iconName: ['build'],
          material: true,
          children: [
            {
              displayName: 'Categoria Cientifica',
              iconName: ['radio_button_unchecked'],
              route: 'cat-science',
              material: true,
              display: true,
            },
            {
              displayName: 'Categoria Docente',
              iconName: ['radio_button_unchecked'],
              route: 'cat-docent',
              material: true,
              display: true,
            },
            {
              displayName: 'Profesión',
              iconName: ['radio_button_unchecked'],
              route: 'profession',
              material: true,
              display: true,
            },
            {
              displayName: 'Sexo',
              iconName: ['radio_button_unchecked'],
              route: 'gender',
              material: true,
              display: true,
            },
            {
              displayName: 'Grupo Sangíneo',
              iconName: ['radio_button_unchecked'],
              route: 'blood-type',
              material: true,
              display: true,
            },
            {
              displayName: 'Tipo Documento Id',
              iconName: ['radio_button_unchecked'],
              route: 'doc-type-id',
              material: true,
              display: true,
            },
            {
              displayName: 'Especialidad',
              iconName: ['radio_button_unchecked'],
              route: 'specialty',
              material: true,
              display: true,
            },
            {
              displayName: 'Estado Civil',
              iconName: ['radio_button_unchecked'],
              route: 'civil_status',
              material: true,
              display: true,
            },
            {
              displayName: 'Nacionalidad',
              iconName: ['radio_button_unchecked'],
              route: 'nationality',
              material: true,
              display: true,
            },
            {
              displayName: 'Raza',
              iconName: ['radio_button_unchecked'],
              route: 'race',
              material: true,
              display: true,
            },
            {
              displayName: 'Pais',
              iconName: ['radio_button_unchecked'],
              route: 'country',
              material: true,
              display: true,
            },
            {
              displayName: 'Provincia',
              iconName: ['radio_button_unchecked'],
              route: 'state',
              material: true,
              display: true,
            },
            {
              displayName: 'Distrito',
              iconName: ['radio_button_unchecked'],
              route: 'municipality',
              material: true,
              display: true,
            },
          ],
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Servicios Clinicos',
      iconName: ['assignment'],
      material: true,
      children: [
        {
          displayName: 'Gestionar Admisión',
          iconName: ['input'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Hitoria Clínica',
          iconName: ['note'],
          children: [
            {
              displayName: 'Historia Clínica',
              iconName: ['radio_button_unchecked'],
              route: 'clinical-services/clinic-history',
              material: true,
              display: true,
            },
            {
              displayName: 'Crear Tabla dinamica',
              iconName: ['radio_button_unchecked'],
              route: 'clinical-services/meta-table',
              material: true,
              display: true,
            },
            {
              displayName: 'Nomenclador Tabla dinamica',
              iconName: ['radio_button_unchecked'],
              route: 'clinical-services/meta-field',
              material: true,
              display: true,
            },
          ],
          material: true,
          display: true,
        },
        {
          displayName: 'Núcleo Funcional',
          iconName: ['center_focus_strong'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Cita',
          iconName: ['today'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Clasificadores',
          iconName: ['build'],
          material: true,
          children: [
            {
              displayName: 'Enfermedades',
              iconName: ['radio_button_unchecked'],
              route: 'cat-science',
              material: true,
              display: true,
            }
          ],
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Recursos Médicos',
      iconName: ['queue'],
      material: true,
      children: [
        {
          displayName: 'Programas',
          iconName: ['dns'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Inventarios',
          iconName: ['view_list'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Movimientos',
          iconName: ['sync_alt'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Esquema de trabajo',
          iconName: ['work'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Nomencladores',
          iconName: ['build'],
          material: true,
          children: [
            {
              displayName: 'Categoria Cientifica',
              iconName: ['radio_button_unchecked'],
              route: 'cat-science',
              material: true,
              display: true,
            },
            {
              displayName: 'Categoria Docente',
              iconName: ['radio_button_unchecked'],
              route: 'cat-docent',
              material: true,
              display: true,
            },
            {
              displayName: 'Profesión',
              iconName: ['radio_button_unchecked'],
              route: 'profession',
              material: true,
              display: true,
            },
            {
              displayName: 'Sexo',
              iconName: ['radio_button_unchecked'],
              route: 'gender',
              material: true,
              display: true,
            },
            {
              displayName: 'Tipo Documento Id',
              iconName: ['radio_button_unchecked'],
              route: 'doc-type-id',
              material: true,
              display: true,
            },
            {
              displayName: 'Especialidad',
              iconName: ['radio_button_unchecked'],
              route: 'specialty',
              material: true,
              display: true,
            },
            {
              displayName: 'Estado Civil',
              iconName: ['radio_button_unchecked'],
              route: 'civil_status',
              material: true,
              display: true,
            },
            {
              displayName: 'Nacionalidad',
              iconName: ['radio_button_unchecked'],
              route: 'nationality',
              material: true,
              display: true,
            },
            {
              displayName: 'Raza',
              iconName: ['radio_button_unchecked'],
              route: 'race',
              material: true,
              display: true,
            },
            {
              displayName: 'Pais',
              iconName: ['radio_button_unchecked'],
              route: 'country',
              material: true,
              display: true,
            },
            {
              displayName: 'Provincia',
              iconName: ['radio_button_unchecked'],
              route: 'state',
              material: true,
              display: true,
            },
            {
              displayName: 'Distrito',
              iconName: ['radio_button_unchecked'],
              route: 'municipality',
              material: true,
              display: true,
            },
          ],
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Estadísticas',
      iconName: ['equalizer'],
      material: true,
      children: [
        {
          displayName: 'Alarmas de stock',
          iconName: ['alarm'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Registros Médicos',
          iconName: ['folder_open'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Indicadores',
          iconName: ['blur_linear'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Programas',
          iconName: ['list_alt'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Epidemiología',
          iconName: ['create_new_folder'],
          route: '',
          material: true,
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Salida',
      iconName: ['assessment'],
      material: true,
      children: [
        {
          displayName: 'Reporte 1',
          iconName: ['picture_as_pdf'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Reporte 2',
          iconName: ['picture_as_pdf'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Reporte 3',
          iconName: ['picture_as_pdf'],
          route: '',
          material: true,
          display: true,
        },
        {
          displayName: 'Reporte 4',
          iconName: ['picture_as_pdf'],
          route: '',
          material: true,
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Almacen',
      iconName: ['store'],
      material: true,
      children: [
        {
          displayName: 'Clasificadores',
          iconName: ['build'],
          material: true,
          children: [
            {
              displayName: 'Medida',
              iconName: ['radio_button_unchecked'],
              route: '',
              material: true,
              display: true,
            }
          ],
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Indicadores',
      iconName: ['store'],
      material: true,
      children: [
        {
          displayName: 'Clasificadores',
          iconName: ['build'],
          material: true,
          children: [
            {
              displayName: 'Subcategoría',
              iconName: ['radio_button_unchecked'],
              route: '',
              material: true,
              display: true,
            },
            {
              displayName: 'Categoría',
              iconName: ['radio_button_unchecked'],
              route: '',
              material: true,
              display: true,
            }
          ],
          display: true,
        },
      ],
      display: true,
    },
    {
      displayName: 'Mi Perfil',
      iconName: ['account_circle'],
      material: true,
      route: 'backend/perfil',
      display: true,
    },
    {
      displayName: 'Configuración',
      iconName: ['settings'],
      material: true,
      route: 'configurations',
      display: true,
    },
  ];

  constructor() {}

  public getNavBackend() {
    return JSON.parse(JSON.stringify(this.navBackend));
  }
}
